webintelligence/gameplat/urls.py
from django.urls import  path
from . import views

app_name = 'gameplat'

urlpatterns = [
    path('numgame/', views.numsgameapp, name='numgame'),
    path('alphgame/', views.alphgameapp, name='alphgame'),
]

webintelligence/mainapp/urls.py
from django.urls import  path
from . import views


urlpatterns = [
    path('', views.mainapp, name='home'),
    path('about/', views.aboutapp, name='about'),
    path('programs/', views.programsapp, name='programs'),
    path('platform/', views.platformapp, name='platform'),
]

webintelligence/webintelligence/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls'), name='home'),
    path('platform/', include('gameplat.urls'), name='platform'),    
]

webintelligence/gameplat/models.py
from django.db import models

# Create your models here.

webintelligence/mainapp/models.py
from django.db import models
from django.contrib.auth.hashers import make_password

class Teacher(models.Model):
    login = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=128)
    last_name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

    def save(self, *args, **kwargs):
        self.password = make_password(self.password)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Student(models.Model):
    login = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=128)
    last_name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    parent_first_name = models.CharField(max_length=100)
    parent_last_name = models.CharField(max_length=100)
    statistics = models.TextField()

    def save(self, *args, **kwargs):
        self.password = make_password(self.password)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

webintelligence/gameplat/views.py
from django.shortcuts import render
from django.http import HttpResponse

def alphgameapp(request):
    return render(request, 'alphtemp.html')

def numsgameapp(request):
    return render(request, 'numtemp.html')

webintelligence/mainapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

def mainapp(request):
    return render(request, 'mainapp/main.html')

def aboutapp(request):
    return render(request, 'mainapp/about.html')

def programsapp(request):
    return render(request, 'mainapp/programs.html')

def platformapp(request):
    return render(request, 'mainapp/platform.html')

webintelligence/gameplat/templates/alphtemp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Найди букву</title>
    <link rel="stylesheet" href="{% static 'gameplat/css/alph.css' %}">
</head>
<body>
    <div class="game-container">
        <div class="header">
            <div class="title">Найди букву</div>
            <div class="settings">
                <div>Уровень обучения</div>
                <div>Размер поля: <span id="field-size">4x4</span></div>
                <div>Режим: <span id="game-mode">Лёгкий</span></div>
                <div>Подсказки: <span id="hints-mode">OFF</span></div>
            </div>
        </div>
        <div class="game-area">
            <div class="target-letter" id="target-letter"></div>
            <div class="letter-grid" id="letter-grid"></div>
        </div>
        <div class="footer">
            <button id="reset-button">Сброс</button>
            <button id="finish-button">Завершить игру</button>
        </div>
    </div>
    <script src="{% static 'gameplat/js/alphscript.js' %}"></script>
</body>
</html>

webintelligence/gameplat/templates/numtemp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Найди пару</title>
    <link rel="stylesheet" href="{% static 'gameplat/css/num.css' %}"> 
</head>
<body>
    <div class="game-container">
        <div class="header">
            <div class="title">Найди пару</div>
            <div class="settings">
                <div>Уровень обучения: 
                    <select id="level-select">
                        <option value="1">Уровень 1</option>
                        <option value="2">Уровень 2</option>
                        <option value="3">Уровень 3</option>
                        <option value="4">Уровень 4</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="game-area">
            <div class="number-grid" id="number-grid"></div>
        </div>
        <div class="footer">
            <button id="reset-button">Сброс</button>
            <button id="finish-button">Завершить игру</button>
        </div>
    </div>
    <script src="{% static 'gameplat/js/numscript.js' %}"></script> 
</body>
</html>

webintelligence/mainapp/templates/mainapp/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Itcity - о нас</title>
    <link type="text/css" href="{% static 'mainapp/css/about.css' %}" rel = "stylesheet" />
</head>

<body>

    <div class="wrapper">  
        <header class="container">
            <nav>
                <ul>
                    <li class ="btn"><a href="{% url 'home' %}">Главная</a></li>
                    <li class="btn"><a href="{% url 'programs' %}">Программы</a></li>
                    <li class="btn"><a href="/Events.html">События</a></li>
                    <li class="btn"><a href="/News.html">Новости</a></li>
                    <li class="btn"><a href="/Blog.html">Блог</a></li>
                    <li class="btn"><a href="/Franch.html">Франшиза </a></li>
                    <li class="btn"><a href="/Contacts.html">Контакты</a></li>
                    <li class="btn"><a href="#">Войти</a></li>
                </ul>
            </nav>
        </header>
    </div>
    <main class="Itcity">
        <div class="hero-wrapper">
            <div class="hero container">
                <div class="hero--block">
                    <div class="hero--info">
                        <h2>Академия</h2>
                        <h1>Развития Интелекта</h1>
                        <p>Присоединяйтесь! Пробный урок - Бесплатно</p>   
                        <button class="btn">ЗАПИСАТЬСЯ</button>    
                    </div>
                </div>
            </div>   
        </div>
        <div class="wrapper-btn">
            <h3>О нас</h3>
            <div class="container-btn">
                <button class="btns btn-1">9 ЛЕТ УСПЕШНОГО ОПЫТА </button>
                <button class="btns btn-2">5000 УЧЕНИКОВ ЕЖЕГОДНО ЗАНИМАЮТСЯ В НАШИХ ЦЕНТРАХ</button>
                <button class="btns btn-3">ГОТОВАЯ МЕТОДИЧЕСКАЯ БАЗА КУРСОВ</button>
                <button class="btns btn-4">18 ФИЛИАЛОВ ОТКРЫТО В РАМКАХ СОБСТВЕННОЙ СЕТИ</button>
                <button class="btns btn-5">УДОБНАЯ СИСТЕМА РАБОТЫ С КЛИЕНТАМИ</button>
                <button class="btns btn-6">6</button>
            </div>
        </div>
    </main>
    <footer>
        <div class="blocks container">
            <div>
                <span class="logo">Logo</span>
                <p> Все права на товарный знак защищены. 
                    Копирование материалов без согласия авторов проекта запрещено ИП Васильева Татьяна Игоревна ИНН 860324040540
                    ОГРН 312860329300037</p>
            </div>
            <div>  
                <h4> 8 922 795 06 40</h4>
                <ul>
                    <li>Онлайн</li>
                    <li>Академия</li>
                    <li>Робототехника</li>
                    <li>Летний лагерь</li>
                </ul>
            </div>
            <div>
                <ul>
                    <li>Договр оферты</li>
                    <li>Политика конфиденциальности</li>
                    <li>Государственная лицензия</li>
                </ul>
            </div>
        </div>
        <hr>
        <p>Сайт разработан ITCLAN - Digital Agency</p>
    </footer>
</body>

</html>

webintelligence/mainapp/templates/mainapp/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Академия развития интелекта</title>
    <link type="text/css" href="{% static 'mainapp/css/main.css' %}" rel = "stylesheet" />
</head>

<body>

    <div class="wrapper">  
        <header class="container">
            <nav>
                <ul>
                    <li class="btn"><a href="{% url 'about' %}">О нас</a></li>
                    <li class="btn"><a href="{% url 'programs' %}">Программы</a></li>
                    <li class="btn"><a href="/Events.html">События</a></li>
                    <li class="btn"><a href="/News.html">Новости</a></li>
                    <li class="btn"><a href="/Blog.html">Блог</a></li>
                    <li class="btn"><a href="/Franch.html">Франшиза </a></li>
                    <li class="btn"><a href="/Contacts.html">Контакты</a></li>
                    <li class="btn"><a href="{% url 'platform' %}">Платформа</a></li>
                </ul>
            </nav>
        </header>
    </div>
    <main class="Itcity">
        <div class="hero-wrapper">
            <div class="hero container">
                <div class="hero--block">
                    <div class="hero--info">
                        <h2>Академия</h2>
                        <h1>Развития Интелекта</h1>
                        <p>Присоединяйтесь! Пробный урок - Бесплатно</p>   
                        <button class="btn">ЗАПИСАТЬСЯ</button>    
                    </div>
                </div>
            </div>   
        </div>

        <div class="programs-wrapper">
            <div id="programs" class="container">
                <h3> Программы</h3>
                <div class="flex">

                    <div id="offline" class="courses-block">
                        <div class="wrapper">
                            <h4>ЗАНЯТИЯ В ЦЕНТРАХ</h4>
                            <p>Классический формат занятий с использованием современных технологий </p>
                        </div>
                        
                        <div class="button-wraper">
                            <button class="btn">...Курсов</button> 
                        </div>
                    </div>

                    <div id="online" class="courses-block">
                        <div class="wrapper">
                            <h4>ОНЛАЙН ОБУЧЕНИЕ</h4>
                            <p>Индивидуальный и удобный для каждого темп обучения. Занимайтесь из дома на интерактивной платформе </p>
                        </div> 

                        <div class="button-wraper">
                            <button class="btn">...Курсов</button> 
                        </div>
                    </div>

                    <div id="ourclass" class="courses-block">
                        <div class="wrapper">
                            <h4>РЕПЕТИТОРЫ 1-11 КЛАСС</h4>
                            <p>Индивидуальные занятия по школьной программе c репетиторами, подготовка к ОГЭ и ЕГЭ</p>
                        </div>

                        <div class="button-wraper">
                            <button class="btn">...Курсов</button> 
                        </div>   
                    </div>

                    <div id="tutoring" class="courses-block">
                        <div class="wrapper">
                            <h4>ЛОГОПЕДЫ</h4>
                            <p>Подберем для вас индивидуального логопеда и организуем удобные онлайн-занятия с гарантией результата.</p>
                        </div>

                        <div class="button-wraper">
                            <button class="btn">...Курсов</button> 
                        </div>
                
                    </div>
                </div>
            </div>
        </div>
        
        <div class="wrapper-info">
            <div class="someinfo">
                <h5>...СЕГОДНЯ - ЭТО: </h5>
                <p>(подсчёт ведется в режиме реального времени)</p>
            </div>    
           
            <div class="content">
                <div class="column1">
                    <img src="{% static 'mainapp/images/person.png' %}" alt="Прошедших обучение">
                    <h6>...</h6>
                    <p>Прошедших обучение</p>
                </div>

                <div class="column2">
                    <img src="{% static 'mainapp/images/_LocationIcon_.png' %}" alt="Аттестованных педагогов">
                    <h6>...</h6>
                    <p>Аттестованных педагогов</p>
                </div>

                <div class="column3">
                    <img src="{% static 'mainapp/images/_LightbulbIcon_.png' %}" alt="Стран">
                    <h6>...</h6>
                    <p>Стран</p>
                </div>
            </div>
        </div>

        <div class="certificate">
            <h7>Свидетельства и сертификаты</h7>
            <div class="carousel">
                <div class="carousel-item"></div>
                <div class="carousel-item"></div>
                <div class="carousel-item"></div>
                <div class="carousel-item"></div>
            </div>
        </div>

        <div class="wrapper-slide">
            <div class="container-slide">
                <h7 class="title">ИНТЕРЕСНОЕ В БЛОГЕ</h7>
                <div class="slider">
                <button class="slide-btn left-button">&larr;</button>
                <div class="card-container">
                    <div class="card"></div>
                    <div class="card"></div>
                    <div class="card"></div>
                </div>
              <button class="slide-btn right-button">&rarr;</button>
            </div>
          </div>
        </div>
    </main>
    <footer>
        <div class="blocks container">
            <div>
                <span class="logo">Logo</span>
                <p> Все права на товарный знак защищены. 
                    Копирование материалов без согласия авторов проекта запрещено ИП Васильева Татьяна Игоревна ИНН 860324040540
                    ОГРН 312860329300037</p>
            </div>
            <div>  
                <h4> 8 922 795 06 40</h4>
                <ul>
                    <li>Онлайн</li>
                    <li>Академия</li>
                    <li>Робототехника</li>
                    <li>Летний лагерь</li>
                </ul>
            </div>
            <div>
                <ul>
                    <li>Договр оферты</li>
                    <li>Политика конфиденциальности</li>
                    <li>Государственная лицензия</li>
                </ul>
            </div>
        </div>
        <hr>
        <p>Сайт разработан ITCLAN - Digital Agency</p>
    </footer>
</body>

</html>

webintelligence/mainapp/templates/mainapp/platform.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Академия развития интелекта</title>
    <link type="text/css" href="{% static 'mainapp/css/platform.css' %}" rel="stylesheet" />
</head>

<body>

    <div class="wrapper">  
        <header class="container">
            <nav>
                <ul>
                    <li class="btn"><a href="{% url 'about' %}">О нас</a></li>
                    <li class="btn"><a href="{% url 'programs' %}">Программы</a></li>
                    <li class="btn"><a href="/Events.html">События</a></li>
                    <li class="btn"><a href="/News.html">Новости</a></li>
                    <li class="btn"><a href="/Blog.html">Блог</a></li>
                    <li class="btn"><a href="/Franch.html">Франшиза </a></li>
                    <li class="btn"><a href="/Contacts.html">Контакты</a></li>
                    <li class="btn"><a href="">Платформа</a></li>
                </ul>
            </nav>
        </header>
    </div>
    <main class="Itcity">
        <!-- Новый блок с выбором игр -->
        <div class="games-wrapper">
            <div id="games" class="container">
                <h3>Выберите игру</h3>
                <div class="flex">
                    <a href="{% url 'gameplat:numgame' %}" class="game-block">
                        <h4>Найди пару</h4>
                        <p>Игра, в которой нужно найти все пары одинаковых карточек.</p>
                    </a>
                    <a href="{% url 'gameplat:alphgame' %}" class="game-block">
                        <h4>Найди букву в алфавите</h4>
                        <p>Игра, в которой нужно найти букву в алфавите.</p>
                    </a>
                </div>
            </div>
        </div>
    </main>
    <footer>
        <div class="blocks container">
            <div>
                <span class="logo">Logo</span>
                <p> Все права на товарный знак защищены. 
                    Копирование материалов без согласия авторов проекта запрещено ИП Васильева Татьяна Игоревна ИНН 860324040540
                    ОГРН 312860329300037</p>
            </div>
            <div>  
                <h4> 8 922 795 06 40</h4>
                <ul>
                    <li>Онлайн</li>
                    <li>Академия</li>
                    <li>Робототехника</li>
                    <li>Летний лагерь</li>
                </ul>
            </div>
            <div>
                <ul>
                    <li>Договр оферты</li>
                    <li>Политика конфиденциальности</li>
                    <li>Государственная лицензия</li>
                </ul>
            </div>
        </div>
        <hr>
        <p>Сайт разработан ITCLAN - Digital Agency</p>
    </footer>
</body>

</html>

webintelligence/mainapp/templates/mainapp/programs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Itcity - о нас</title>
    <link type="text/css" href="{% static 'mainapp/css/programs.css' %}" rel = "stylesheet" />
</head>

<body>

    <div class="wrapper">  
        <header class="container">
            <nav>
                <ul>
                    <li class ="btn"><a href="{% url 'home' %}">Главная</a></li>
                    <li class ="btn"><a href="{% url 'about' %}">О нас</a></li>
                    <li class="btn"><a href="/Events.html">События</a></li>
                    <li class="btn"><a href="/News.html">Новости</a></li>
                    <li class="btn"><a href="/Blog.html">Блог</a></li>
                    <li class="btn"><a href="/Franch.html">Франшиза </a></li>
                    <li class="btn"><a href="/Contacts.html">Контакты</a></li>
                    <li class="btn"><a href="#">Войти</a></li>
                </ul>
            </nav>
        </header>
    </div>
    <main class="Itcity">
        <div class="hero-wrapper">
            <div class="hero container">
                <div class="hero--block">
                    <div class="hero--info">
                        <h2>Академия</h2>
                        <h1>Развития Интелекта</h1>
                        <p>Присоединяйтесь! Пробный урок - Бесплатно</p>   
                        <button class="btn">ЗАПИСАТЬСЯ</button>    
                    </div>
                </div>
            </div>   
        </div>
        <div class="wrapper-btn">
            <h3>Программы</h3>
            <div class="container-btn">
                <button class="btns btn-1">АНГЛИЙСКИЙ ЯЗЫК </button>
                <button class="btns btn-2">МАТЕМАТИКА</button>
                <button class="btns btn-3">МЕНТАЛЬНАЯ АРИФМЕТИКА</button>
                <button class="btns btn-4">СКОРОЧТЕНИЕ</button>
                <button class="btns btn-5">ПРОГРАММИРОВАНИЕ</button>
                <button class="btns btn-6">РАЗВИТИЕ ПАМЯТИ</button>
            </div>
        </div>
    </main>
    <footer>
        <div class="blocks container">
            <div>
                <span class="logo">Logo</span>
                <p> Все права на товарный знак защищены. 
                    Копирование материалов без согласия авторов проекта запрещено ИП Васильева Татьяна Игоревна ИНН 860324040540
                    ОГРН 312860329300037</p>
            </div>
            <div>  
                <h4> 8 922 795 06 40</h4>
                <ul>
                    <li>Онлайн</li>
                    <li>Академия</li>
                    <li>Робототехника</li>
                    <li>Летний лагерь</li>
                </ul>
            </div>
            <div>
                <ul>
                    <li>Договр оферты</li>
                    <li>Политика конфиденциальности</li>
                    <li>Государственная лицензия</li>
                </ul>
            </div>
        </div>
        <hr>
        <p>Сайт разработан ITCLAN - Digital Agency</p>
    </footer>
</body>

</html>